### ISSUE TITLE
Export to CSV beyond ASCII

### ISSUE THREAD

**Issue by BeyondConventionalBoundaries** [GraffitiProjectINDIGO/GRAPHIS#15]
- When I save the transcript "IT´S LIKE ALL DAY", the CSV displays "ITÂ´S LIKE ALL DAY"
- when I save the transcript "FÜR NNA VON NARD", the CSV displays "FÃœR NNA VON NARD"

**Comment by MartinW-S2M** [comment]
Utf8 is the encoding of the csv. This only seems to be a problem for excel if you open the csv. Notepad, Editor, Google Docs opens correct. Also loading the CSV via the excel open import text|csv does automatically choose utf8
