### ISSUE TITLE
Creation of point, not region

### ISSUE THREAD

**Issue by BeyondConventionalBoundaries** [GraffitiProjectINDIGO/GRAPHIS#18]
<img width="386" alt="image" src="https://github.com/GraffitiProjectINDIGO/GRAPHIS/assets/85742286/f8d024a6-4cbc-43c9-a302-b59e07dc0eae">
I think that I wanted to make a region, but thought I should first save the previous region and then I noticed there was this new 0 dimensional region.

**Comment by MartinW-S2M** [comment]
Was able to reporoduce the bug. Creating a Rectangle and than immediatly click again right button seems to create a rectangle with size 0.

**Comment by MartinW-S2M** [comment]
Also implementing to prevent adding polygon vertices with same coordinates as the previous one if you severel time click right button on the same position or left click.
